sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t test_react -f dockerfile.dev .

script:
  - docker run -e CI=true test_react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'demo_react_docker'
  env: 'demo_react_docker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-318386363514'
  bucket_path: 'demo_react_docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
